apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaexpress-deployment
  labels:
    app: javaexpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaexpress
  template:
    metadata:
      labels:
        app: javaexpress
    spec:
      containers:
        - name: javaexpress
          image: andrei4455/springjavaexpress-docker-demo:springjavaexpress-docker-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: javaexpress-service
spec:
  type: NodePort
  selector:
    app: javaexpress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32250
