namespace: default

deployment:
  name: javaexpress2
  app: javaexpress2
  replicaCount: 1
  image: your-image:latest
  imagePullPolicy: IfNotPresent
  containerPort: 8080

service:
  name: javaexpress2
  type: ClusterIP
  app: javaexpress2
  protocol: TCP
  port: 80
  targetPort: 8080
  externalIPs: []