apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaexpress2-deployment
  namespace: {{ .Values.namespace}}
  labels:
    app: javaexpress2
spec:
  replicas: {{ .Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: javaexpress2
  template:
    metadata:
      labels:
        app: javaexpress2
    spec:
      containers:
        - name: javaexpress2
          image: {{ .Values.deployment.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1