apiVersion: v1
kind: Service
metadata:
  name: javaexpress5-service
spec:
  type: NodePort
  selector:
    app: javaexpress5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32320